tdevPath: ../teaching-dev
expectedTdevBranch: main
trackedElements:
    - src: docusaurus.config.ts
      dst: docusaurus.config.ts
    - src: .devcontainer/devcontainer.json
      dst: .devcontainer/devcontainer.json
    - src: .github/workflows/prettier-check.yml
      dst: .github/workflows/prettier-check.yml
    - src: src/
      dst: src
      ignore:
          - pages/index.tsx
          - pages/__index.tsx
          - pages/.gitignore
          - theme/**
    - src: src/theme/Root.tsx
      dst: src/theme/Root.tsx
    - src: packages/tdev/excalidoc/
      dst: packages/tdev/excalidoc
    - src: packages/tdev/remark-pdf/
      dst: packages/tdev/remark-pdf
    - src: packages/tdev/remark-graphviz/
      dst: packages/tdev/remark-graphviz
    - src: updateSync/
      dst: updateSync
      ignore:
          - sync-onboarding.ts
          - clean-onboarding.ts
    - src: tsconfig.tdev.json
      dst: tsconfig.json
    - src: .prettierrc
      dst: .prettierrc
    - src: .prettierignore
      dst: .prettierignore
    - src: vitest.config.ts
      dst: vitest.config.ts
watchedElements:
    - .babel.config.js
    - package.json
    - .env.example
    - src/theme/
