tdevPath: ../teaching-dev
expectedTdevBranch: main
trackedElements:
    - src: docusaurus.config.ts
      dst: docusaurus.config.ts
    - src: src/
      dst: src
      ignore:
          - pages/index.tsx
          - pages/__index.tsx
          - pages/.gitignore
          - theme/**
    - src: updateSync/
      dst: updateSync
    - src: tsconfig.json
      dst: tsconfig.json
    - src: .prettierrc
      dst: .prettierrc
    - src: .prettierignore
      dst: .prettierignore
    - src: vitest.config.ts
      dst: vitest.config.ts
watchedElements:
    - .babel.config.js
    - package.json
    - .env.example
